### ISSUE TITLE
autocompletion delay?

### ISSUE THREAD

**Issue by tmc** [lifepillar/vim-mucomplete#107] opened 2018-07-23 01:16 UTC
completion can be a little overzealous (example: git commit messages).

Could this only trigger after a short (configurable) period of inactivity?

**Comment by lifepillar** [comment] 2018-07-23 07:12
Currently, this is not supported, but the following might work: edit `autoload/mucomplete.vim` and change this line:

```vim
autocmd TextChangedI  * noautocmd call mucomplete#act_on_textchanged()
```

into this:

```vim
autocmd CursorHoldI  * noautocmd call mucomplete#act_on_textchanged()
```

Then you should be able to delay autocompletion by setting `updatetime` to a suitable value (see `:h CursorHold`). Let me know if that does what you want.

**Comment by tmc** [comment] 2018-07-30 15:49
👍

**Comment by kristijanhusak** [comment] 2018-08-28 13:57
Just a note that this is not working in neovim due to this issue https://github.com/neovim/neovim/issues/3757

**Comment by kristijanhusak** [comment] 2018-08-28 14:28
@lifepillar what do you think about adding timers instead of CursorHoldI and updatetime?

**Comment by lifepillar** [comment] 2018-08-28 18:21
I have browsed the issue quickly, but there's a comment mentioning that the root cause of that issue might affect timers as well.

I am not very keen to implement a possibly complex feature just to workaround a bug in NeoVim, especially if the new feature might turn to be buggy, too.

The real question is: would an implementation of delayed completion based on timers offer any real advantages over the current implementation?

**Comment by lifepillar** [comment] 2018-08-28 18:32
A PR is welcome!

**Comment by lifepillar** [comment] 2018-09-05 11:59
Delayed completion with timers has been merged into master. I have changed the name of the option from `g:mucomplete#delayed_completion` to `g:mucomplete#completion_delay`. Please take note and sorry for the inconvenience.

@kristijanhusak Thanks for your contribution!

**Closed by lifepillar** 2018-09-05 11:59 UTC
Labels: enhancement
