### ISSUE TITLE
'spel' precedes 'keyn' even if listed last in g:mucomplete#chains

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-mucomplete#7] opened 2016-10-24 02:26 UTC
Under Vim 8.45, if
```vim
let g:mucomplete#chains = {
      \ 'default':  ['keyn, 'spel']
      \ }
```
and `set spell spelllang=en` and `set complete=k`, then  hit `<tab>` after `cras`.

Expected: the menu keyword completion menu appears.
What happens: the spell correction completion menu appears.

**Comment by lifepillar** [comment] 2016-10-24 06:43
That is expected behavior: starting with an empty buffer, after inserting `cras<tab>` local keyword completion does not return any result, so the next method is tried, which in this case is spelling suggestions. The value of `complete` is irrelevant here, because the `'spel'` method uses `<c-x>s`, not `<c-n>` or `<c-p>`.

If you type `crash cras<tab>` instead, then local keyword completion is used.

**Comment by Konfekt** [comment] 2016-10-24 10:31
Ok, it should be `c-n` instead of `keyn`. Under Vim 8.45, set
```
let g:mucomplete#chains = {
                  \ 'default':  ['c-n', 'spel']
                  \ }
set spell spelllang=en 
set complete=k
```
and hit <tab> after cras. 
Expected: `crash`. 
Result: `Crashed`.

**Comment by lifepillar** [comment] 2016-10-24 19:19
Cannot reproduce, I get `crash` :/

**Comment by lifepillar** [comment] 2016-10-24 19:24
Can you

```
set showmode
set shortmess-=c
```

and see which completion method is triggered?

**Comment by Konfekt** [comment] 2016-10-24 19:39
It shows `Spelling Suggestion (1 of 100)`.

**Comment by lifepillar** [comment] 2016-10-24 19:48
Weird. What happens if you press `<c-n>` after `cras`?

It may be a manifestation of the problem mentioned in the Known Issues section of the Readme.

**Comment by Konfekt** [comment] 2016-10-24 19:51
The cause is 
```vim
set dictionary+=/usr/share/dict/words
```

**Comment by lifepillar** [comment] 2016-10-25 19:38
Closing as duplicate of https://github.com/lifepillar/vim-mucomplete/issues/14.

**Closed** 2016-10-25 19:40 UTC
