### ISSUE TITLE
add mappings to enter subdirectory in path completion

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-mucomplete#20] opened 2016-10-28 23:28 UTC
Perhaps this mapping is useful when completing file paths, and could become an option or make it into the docs: 

When completing a file path (say `/home/` and hitting `<tab>`) , and after having chosen a directory by iteratively hitting `<tab>` (say `/home/user`) , hitting `/` allows you to continue completing the file names inside it (that is, `/home/user/...`:

``` vim
let s:slash = has('win32') ? '\' : '/'
exec 'inoremap <expr> ' . s:slash . ' '
      \ . '(pumvisible() && <SID>isBehindDir()) ?'
      \ . '"<C-Y><C-X><C-F>" : "' . s:slash . '"'

let s:escaped_slash = escape(s:slash, '\')
function! s:isBehindDir()
  return getline('.') =~# '\f\+` . s:escaped_slash . '$' 
endfunction
```

**Comment by josefson** [comment] 2016-10-29 02:52
In your example, when i hit ```/home/``` and press tab until i select the user subfolder i already get a / at the end: ```/home/user/```. I can't hit tab nor / to try another nested folder, what i have been doing is <c-y> to accept/finish completion and hit another tab to keep going.
This behavior that @Konfekt is talking about is the same YCM uses and i think it's more intuitive. So we shouldn't get the latest ```/``` and get the tab trigger when we hit ```/``` like in the example bellow. I think that would be a good enhancement.
![Image PathCompletion]
(http://i.imgur.com/qd4e1IF.gif)

**Comment by lifepillar** [comment] 2016-10-29 08:56
>So we shouldn't get the latest /

MUcomplete uses Vim's default file completion, so that is not possible.

**Comment by Konfekt** [comment] 2016-11-01 09:39
Yes, Vim uses a trailing slash / to indicate a Directory whereas YCM adds an extra column to indicate either directory or file. So the slash is already there. 

With these mappings, Vim works like ZSH, for example, where a trailing slash indicates a Directory as well,but sill hitting / enters the selected subfolder.

**Comment by lifepillar** [comment] 2016-11-02 08:44
The following setting may help, too:

```vim
let g:mucomplete#trigger_auto_pattern = { 'default' : g:mucomplete#pathsep . '$\|\k\k$' }
```

After completing part of a path, you may type any character followed by backspace to have the pop-up menu appear again with a list of subdirectories. Not ideal, but it works without any changes in µcomplete.

**Comment by lifepillar** [comment] 2016-11-09 21:23
I've tried @Konfekt's idea and it seems a good compromise to me, well fit to the way Vim's file completion works (and it may be familiar to zsh users, too). I am a bit reluctant, though, to remap such a common character such as a (back)slash. It could be offered as an option.

On the other hand, it shouldn't be difficult to implement YCM's file completion in a function, which could be used as an additional completion method, similar to the way `'ulti'` is implemented. YCM does it in Python, I think, but it could be done in pure Vim, too. The tricky part would be making it portable and robust: the Dirvish plugin might be a source of inspiration. Pull requests are welcome :)

**Comment by lifepillar** [comment] 2016-11-09 21:39
>the Dirvish plugin might be a source of inspiration

On a second thought, this might not be a good idea, because µcomplete is in the public domain, while Dirvish is licensed through the GPL.

**Comment by Konfekt** [comment] 2016-11-10 09:45
It would have to reimplement the completion list from scratch, by `systemlist( has('win32') ? 'ls' : 'dir')`? Because Vim's file completion is robust, and mu-complete already supports it, it seems overkill to add another, untested, file completion to avoid mapping slash in insert mode.

But making it a documented option, is a good compromise.

**Comment by lifepillar** [comment] 2016-11-10 18:03
>It would have to reimplement the completion list from scratch

Yes, but I'd rather do something along these lines:

```vim
fun! PathCompleteDraft() abort
  let l:prefix = matchstr(strpart(getline('.'), 0, col('.') - 1), '\f\+$')
  if strlen(l:prefix) > 0
    let l:candidates = map(glob(l:prefix.'*', 0, 1, 1),
          \  '{
          \      "word": v:val,
          \      "menu": (isdirectory(v:val) ? "[dir]" : "[file]")
          \   }')
    if !empty(l:candidates)
      call complete(col('.') - len(l:prefix), l:candidates)
    endif
  endif
  return ''
endf
```

This is not devoid of its own difficulties, though: to make it work like YCM, some code should be executed at `CompleteDone`, too. Complicating µcomplete only for this use case seems overkill for me, too.

**Comment by lifepillar** [comment] 2016-11-10 20:51
@Konfekt @josefson Would you mind trying the `path-completion` branch? I have added an experimental `'path'` method, which behaves similarly to what @josefson has suggested. The `'file'` method is unchanged for now.

**Comment by josefson** [comment] 2016-11-11 01:04
As i see the branch is behaving like this:

- The '/' character auto triggers path completion
- It looks like it is not using vim path completion candidates lists anymore. It doesn't present the '/' on directories, instead [file|dir].
- The above behavior allow us to hit '/' and keep triggering path completion.
- Even when backspacing something up to hit a '/' path completion is triggered

> I have added an experimental 'path' method, which behaves similarly to what @josefson has suggested.

I think you are being modest @Konfekt. From what i have tested so far, it behaves exactly like that.

Let me take this opportunity  and thank you again for the work input you have been putting in this amazing plugin. A simplistic, yet fresh concept in autocomplete land for vim, which brought together some advantages that i didn't see put together before.
I hope vimland get to test it, and maybe enjoy it like i am. I know you deserve some love for the great work you have been putting into it.
Thanks man.

**Comment by lifepillar** [comment] 2016-11-11 08:01
I have also implemented @Konfekt's suggestion, but a bit differently. Now `'file'` completion works as follows: when accepting a menu entry with `<c-y>`, file completion is triggered again. Using `<c-y>` is standard Vim's mapping, and there is no need to remap `/` (of course, a user may still do it, if desired).

Please try the `path-completion` branch and let me know how it works for you. I'd like feedback especially from Windows users, since I cannot test in Windows.

**Comment by lifepillar** [comment] 2016-11-11 08:14
@josefson Thanks for the kind words. I've got much from Vim and the Vim community, giving something back is only fair. Plus, it's fun!

**Comment by lifepillar** [comment] 2016-11-11 14:43
Just wondering: can YCM deal with paths containing spaces? Vim's file completion does not.

**Comment by josefson** [comment] 2016-11-11 20:20
1. I tested the <c-y> behavior on ```file``` completion-method(path-completion branch) and it is also very satisfying. I could have lived with it.

  * Oh i see what is happening, whenever a spaced [path|file]name is inserted, either <c-y> on `file` or / on `path` get out of the scope method. That should be a pain, for windows users mainly, i think most unix users avoid the use of spaces on filenaming. Good catch.

2. About YCM, i went through the pain of installing it to test your request, and yes it recognizes and keep completing over spaced directories:
![Image ycm_spaced_path]
(https://i.imgur.com/DgFLJgF.gif)

**Comment by lifepillar** [comment] 2016-11-12 10:49
@Konfekt @josefson Both the features you have requested have been implemented and are available in the current master, so I'm closing this. Please open new issues if you need to report bugs.

**Comment by lifepillar** [comment] 2016-11-12 10:49
…and don't forget to read the docs!

**Comment by Konfekt** [comment] 2016-11-13 09:26
Well done!

**Comment by Konfekt** [comment] 2016-11-13 10:16
The documentation is  off: The mapping of the thread is a différent one. The check if a file path is being completed is missing. Otherwise / ends completion in général. That's not intended.

**Comment by lifepillar** [comment] 2016-11-13 14:55
I have updated the documentation: do you still find that there is something unclear?

Re the unintended behaviour, can you please elaborate?

**Comment by Konfekt** [comment] 2016-11-13 19:49
Intended, no problem with indentation. The point was that
```vim
inoremap <expr> / pumvisible() ? "\<c-y>" : '/'
```
does not check if one is completing a file path. Thus, `/` will always end completion. That's only intended, that is, wanted, when completing file paths.

The original mapping
```vim
let s:slash = has('win32') ? '\' : '/'
exec 'inoremap <expr> ' . s:slash . ' '
      \ . '(pumvisible() && <SID>isBehindDir()) ?'
      \ . '"<C-Y><C-X><C-F>" : "' . s:slash . '"'

let s:escaped_slash = escape(s:slash, '\')
function! s:isBehindDir()
  return getline('.') =~# '\f\+` . s:escaped_slash . '$' 
endfunction
```
makes this additional check. (Note that now `<c-x><c-f>` is superfluous.)

**Comment by lifepillar** [comment] 2016-11-13 20:56
Ah, right. I have updated the example in the documentation, adding your code (slightly modified to make it more general).

**Comment by Konfekt** [comment] 2016-11-14 09:05
Perfect!

**Closed** 2016-11-14 20:04 UTC
Labels: enhancement
