### ISSUE TITLE
completion entries skipped if 'c-n' before 'omni'

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-mucomplete#9] opened 2016-10-24 12:41 UTC
Under Vim 8.45, set
```
let g:mucomplete#chains = {
                  \ 'default':  ['c-n', 'omni']
                  \ }
set spell spelllang=en 
set complete=k
set completeopt=menu,menuone

set omnifunc=syntaxcomplete#Complete
```
and hit <tab> after `cras` in a file of type `text`. 
Expected:  the `c-n` completion menu for `cras` appears. 
Result: `cras` is completed to the first option of the `c-n` completion menu.

This does not happen 
- either with `omnifunc=`,
- or if `omni` comes before `c-n`.

**Comment by lifepillar** [comment] 2016-10-24 16:00
I am not sure I  am understanding the issue. The order of the completion chain doesn't matter because omni completion does not return any result anyway. I get `cras` completed to `crash` whether `omnifunc` is defined or not, and whether `'omni'` comes before `'c-n'` or not. And when hitting `<tab>` the first entry in the popup menu is always automatically selected (this is by design). Isn't this what you expect?

**Comment by Konfekt** [comment] 2016-10-24 19:35
Yes, all fine. But the popup menu is not showing. Hitting `<c-p>` yields the popup menu that shows the possible completions, but `<c-p>` does not.

**Comment by Konfekt** [comment] 2016-10-25 10:11
Note that this issue also depends on
```vim
set dictionary+=/usr/share/dict/words`
```
(or any other text file).

**Comment by lifepillar** [comment] 2016-10-25 19:14
Ok, now I can reproduce. It is the problem described in the Readme.

**Comment by lifepillar** [comment] 2016-10-25 19:38
Closing as duplicate of https://github.com/lifepillar/vim-mucomplete/issues/14.

**Closed by lifepillar** 2016-10-25 19:38 UTC
Labels: help wanted
