### ISSUE TITLE
Error detected while processing autoload/mucomplete.vim

### ISSUE THREAD

**Issue by sunaku** [lifepillar/vim-mucomplete#2] opened 2016-10-23 23:43 UTC
With this line in my vimrc:

    let g:mucomplete#enable_auto_at_startup = 1

I get this error at NeoVim 0.1.5 startup:

```
Error detected while processing autoload/mucomplete.vim:
line   40:
E15: Invalid expression: > 1 } " Try always
E15: Invalid expression: { _ -> 1 } " Try always
line   51:
E15: Invalid expression: > strlen(&l:dictionary) > 0 },     'file':  { t -> t =~# '/' },     'omni':  { t -> strlen(&l:omnifunc) > 0 },     'spel':  { t -> &l:spell },     'tags':  { t -> !empty(tagfiles()) },     'thes':  { t -> strlen(&l:thesaurus) > 0 },     'user':  { t -> strlen(&l:completefunc) > 0 }   }, get(get(g:, 'mucomplete#can_complete', {}), 'default', {})) }, get(g:, 'mucomplete#can_complete', {}), 'keep')
E116: Invalid arguments for function extend({     'dict':  { t -> strlen(&l:dictionary) > 0 },     'file':  { t -> t =~# '/' },     'omni':  { t -> strlen(&l:omnifunc) > 0 },     'spel':  { t -> &l:spell },     'tags':  { t -> !empty(tagfiles()) },     'thes':  { t -> strlen(&l:thesaurus) > 0 },     'user':  { t -> strlen(&l:completefunc) > 0 }   }, get(get(g:, 'mucomplete#can_complete', {}), 'default', {})) }, get(g:, 'mucomplete#can_complete', {}), 'keep')
E116: Invalid arguments for function extend({ 'default' : extend({     'dict':  { t -> strlen(&l:dictionary) > 0 },     'file':  { t -> t =~# '/' },     'omni':  { t -> strlen(&l:omnifunc) > 0 },     'spel':  { t -> &l:spell },     'tags':  { t -> !empty(tagfiles()) },     'thes':  { t -> strlen(&l:thesaurus) > 0 },  'user':  { t -> strlen(&l:completefunc) > 0 }   }, get(get(g:, 'mucomplete#can_complete', {}), 'default', {})) }, get(g:, 'mucomplete#can_complete', {}), 'keep')
E15: Invalid expression: extend({ 'default' : extend({     'dict':  { t -> strlen(&l:dictionary) > 0 },     'file':  { t -> t =~# '/' },     'omni':  { t -> strlen(&l:omnifunc) > 0 },     'spel':  { t -> &l:spell },     'tags':  { t -> !empty(tagfiles()) },     'thes':  { t -> strlen(&l:thesaurus) > 0 },     'user':  { t -> strlen(&l:completefunc) > 0 }   }, get(get(g:, 'mucomplete#can_complete', {}), 'default', {})) }, get(g:, 'mucomplete#can_complete', {}), 'keep')
Press ENTER or type command to continue
```

**Comment by lifepillar** [comment] 2016-10-24 06:31
Closed as duplicate of #1.

**Closed by lifepillar** 2016-10-24 06:31 UTC
