### ISSUE TITLE
Deletes part of typed word if suggested on ENTER

### ISSUE THREAD

**Issue by bbtdev** [lifepillar/vim-mucomplete#95] opened 2018-03-16 19:25 UTC
Hello,
So for example if I type completely "else" and "else" is suggested in the popup and I press ENTER it deletes part of the word. It forces me to select it from the popup.
It is annoying when typing words that you type very fast and don't need autocomplete.

**Comment by lifepillar** [comment] 2018-03-16 20:16
Please provide more details (at least µcomplete's settings in your `vimrc`and buffer's filetype), because I cannot reproduce your issue. Also, have you read `:help mucomplete-troubeshooting`? Can you reproduce your issue when you run `vim` with `vim -u troubleshooting_vimrc.vim`?

**Comment by bbtdev** [comment] 2018-03-17 14:44
Thank you for your response,

This happens also when I use - u troubleshooting_vimrc.vim

This is what I added to the troubleshooting_vimrc.vim:
set runtimepath+=/home/bogdan/.vim/plugged/vim-mucomplete " CHANGE THIS

```
" Optionally add additional configuration below this line
setglobal complete-=t
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['c-p']
let g:mucomplete#chains.vim = ['c-p', 'cmd']
let g:mucomplete#chains.ruby = ['c-p', 'tags', 'omni']
set completeopt+=menuone
set completeopt+=noselect
set completeopt+=noinsert
let g:mucomplete#always_use_completeopt = 1
let g:mucomplete#enable_auto_at_startup = 1
```
I recorded what's happening in a gif, but I can't upload it to github for some reason, here is the link:
https://gfycat.com/TimelyAcidicAfricanpiedkingfisher

When the text dissapears I'm pressing enter

**Comment by bbtdev** [comment] 2018-03-17 15:12
This has to with the vim c_x c_p, i've test a pure vimrc, with only:
```
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype plugin on    " Enable filetype-specific plugins
set number " sets numbering
set hidden " hide buffer errors
set tabstop=2 shiftwidth=2 expandtab " tab and spaces
filetype indent on    " Enable filetype-specific indenting, vim-plug does this auto

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o " no comment on new lines
set wrap " wrap lines visually
set wildmenu " pressing tab in command
set completeopt+=menuone
set completeopt+=noselect
set completeopt+=noinsert
```
Behaviour:
If you have the test in your buffer
Type te then c_x c_p
type s, but you want only tes so you press enter
it deletes s

Is there anyway we can fix this? Because it ruins the mucomplete flow

**Comment by bbtdev** [comment] 2018-03-17 15:28
Fixed by swithing in the complete chain to 'c-n' instead of 'c-p'
Appologies if this was some kind of obvious solution, still learning vim innerworkings!

But now I have to press ENTER twice, if I want to go on new line, do I open an issue? Or this is another obvious vim situation

**Comment by lifepillar** [comment] 2018-03-17 18:01
Ok, now I can reproduce it. I'll investigate further later. It might be related to https://github.com/lifepillar/vim-mucomplete/issues/61.

**Comment by lifepillar** [comment] 2018-03-17 19:19
>If you have the test in your buffer
>Type te then c_x c_p
>type s, but you want only tes so you press enter
>it deletes s

>Is there anyway we can fix this? Because it ruins the mucomplete flow

I can confirm that this is a duplicate of https://github.com/lifepillar/vim-mucomplete/issues/61, which in turn is related to https://github.com/vim/vim/issues/1645.

>Fixed by swithing in the complete chain to 'c-n' instead of 'c-p'  […]
>But now I have to press ENTER twice, if I want to go on new line, do I open an issue?

No, that is how Vim behaves. You can reproduce it without µcomplete. Just type:

```
else
elseif
el<c-x><c-n>
```

then press `<c-p>`, if necessary, until no match is selected, then type `s` and press Enter. The menu is dismissed, but the cursor stays on the same line.

You should be able to work around that by putting the following in your `vimrc`:

```vim
    fun! s:my_cr()
      return pumvisible() ? "\<c-y>" : ""
    endf
    imap <silent> <expr> <sid>(MyCR) <sid>my_cr()
    imap <unique> <cr> <sid>(MyCR)<plug>(MUcompleteCR)
```

This maps Enter  to `<c-y><cr>` when the pop-up menu visible, otherwise it just sends `<cr>`. If that fixes your issue, I may consider implementing it inside µcomplete.

**Comment by lifepillar** [comment] 2018-03-17 19:30
Btw, note that the proposed workaround should fix your issue with `'c-n'`, but not the one with `'c-p'` (which is a Vim bug).

**Comment by lifepillar** [comment] 2018-03-17 20:25
I have implemented the proposed workaround. Please upgrade to the current master and let me know how it works for you.

**Comment by lifepillar** [comment] 2018-03-17 20:39
No, sorry, I had to revert the change. Mapping Enter to `<c-y><cr>` does not always work correctly.

**Comment by bbtdev** [comment] 2018-03-17 20:47
What about <c-e><c-r>?
Also, please take in consideration compatibility with vim-endwise. It's an extremely popular plugin.

I just got home, so I'm starting testing again. Before I left this worked:
inoremap < expr >  < CR > pumvisible() ? "<C-e><CR>" : "<CR>"
But it's incompatible with endwise

**Comment by lifepillar** [comment] 2018-03-17 22:01
The current master has a new option. If you set:

```vim
let g:mucomplete#smart_enter = 1
```

µcomplete will make Enter equivalent to `<c-y><cr>`, so it should always insert a new line.

**Comment by lifepillar** [comment] 2018-03-17 22:11
In my limited testing, `let g:mucomplete#smart_enter = 1` seems to play well with endwise.

**Comment by bbtdev** [comment] 2018-03-17 23:28
Testing
I. With vim-endwise:
Now I have to press ENTER 3 times.
STEPS:
-open vim the troubleshoot rc below
-on the new buffer type testing, press ENTER
-type tes, for a new line you need to press ENTER 3 times

 The troubleshoot vimrc:
set runtimepath+=/home/bogdan/.vim/plugged/vim-mucomplete " CHANGE THIS
set runtimepath+=/home/bogdan/.vim/plugged/vim-endwise/

```
" Optionally add additional configuration below this line
setglobal complete-=t
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['c-n']
let g:mucomplete#chains.vim = ['c-n', 'cmd']
let g:mucomplete#chains.ruby = ['c-n','tags']
set completeopt+=noselect
set completeopt+=noinsert
let g:mucomplete#always_use_completeopt = 1
let g:mucomplete#enable_auto_at_startup = 1
set wildmenu
set wildmode=list:longest,full
let g:mucomplete#smart_enter = 1
```

II. Without Endwise and troubleshoot vimrc:

No change, I have to press ENTER 2 times

troubleshoot rc:
```
set runtimepath+=/home/bogdan/.vim/plugged/vim-mucomplete " CHANGE THIS
"set runtimepath+=/home/bogdan/.vim/plugged/vim-endwise/

" Optionally add additional configuration below this line
setglobal complete-=t
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['c-n']
let g:mucomplete#chains.vim = ['c-n', 'cmd']
let g:mucomplete#chains.ruby = ['c-n','tags']
set completeopt+=noselect
set completeopt+=noinsert
let g:mucomplete#always_use_completeopt = 1
let g:mucomplete#enable_auto_at_startup = 1
set wildmenu
set wildmode=list:longest,full
let g:mucomplete#smart_enter = 1
```

Can you share the vimrc that you tested with? Cheers

**Comment by lifepillar** [comment] 2018-03-18 08:25
If you you endwise, you also need to put this in your `vimrc`:

```vim
imap <Plug>MyCR <Plug>(MUcompleteCR)
imap <cr> <Plug>MyCR
```

Please add the two lines above and try again.

**Comment by bbtdev** [comment] 2018-03-18 08:53
Works!
I have to work today on a ruby/rails project so I would use this setup and test it properly and post if I find something else!

Thank you for your work! Congratulations on making such an awesome plugin!!

**Comment by lifepillar** [comment] 2018-03-18 08:55
Good to know! I will probably update µcomplete so that remapping `<cr>` won't be needed any longer. Stay tuned!

**Comment by lifepillar** [comment] 2018-03-18 08:58
I will keep this open, because the original issue (deleted text when using `'keyp'` or `'c-p'`) still exists.

If you find other endwise related bugs, please open a new issue.

**Comment by lifepillar** [comment] 2018-03-22 19:05
Closing this, because:

- the bug can be reproduced without µcomplete (see https://github.com/vim/vim/issues/1645);
- a workaround consists in using `'c-n'` and/or `'keyn'` instead of `'c-p'` and/or `'keyp'`, respectively, possibly with this line in your `vimrc`:

```vim
let g:mucomplete#popup_direction = { 'keyn': -1, 'c-n': -1 }
```

**Closed by lifepillar** 2018-03-22 19:05 UTC

**Comment by lifepillar** [comment] 2018-04-26 06:27
FYI, starting with Vim 8.0.1731, this issue should be fixed, so `'keyp'` and `'c-p'` should not cause character deletions any longer.
