### ISSUE TITLE
Mucomplete expand snippet inserts mucomplete#ultisnips#expandsnippet

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#125] opened 2018-09-10 09:01 UTC
Old bug started again. btw.

**Comment by lifepillar** [comment] 2018-09-10 14:09
How to reproduce? Are you using the configuration suggested in MUcomplete's help?u

**Comment by midnio** [comment] 2018-09-10 16:30
Yeah

**Comment by midnio** [comment] 2018-09-11 07:40
Everytime that I use Enter key, it inserts it.

**Comment by midnio** [comment] 2018-09-11 07:53
Then, I do not want to use ultisnips. I want to use snipmate, how to integrate it with mucomplete to expand it as same with ultisnips? (Expand it in the menu)

**Comment by lifepillar** [comment] 2018-09-11 14:08
For SnipMate, see `:help mucomplete-compatibility`.

**Comment by crivotz** [comment] 2018-11-05 14:39
Same problem with ultisnips

```
" =============================================================================
" ULTISNIPS
" =============================================================================
let g:UltiSnipsExpandTrigger = "<f6>"
let g:UltiSnipsJumpForwardTrigger = "<c-b>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"
let g:UltiSnipsSnippetDirectories=["UltiSnips"]

" =============================================================================
" VIM-MUCOMPLETE
" =============================================================================
set completeopt+=menuone,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['ulti', 'omni', 'path', 'keyn', 'keyp', 'file']
let g:jedi#popup_on_dot = 1
inoremap <silent> <expr> <cr>
      \ mucomplete#ultisnips#expand_snippet("\<cr>")
```

**Comment by lifepillar** [comment] 2018-11-06 17:18
@crivotz I cannot reproduce it. Please put your configuration in `troubleshooting_vimrc.vim` (inside MUcomplete's folder). Don't forget to also add Ultisnips and Snippets to your `runtimepath`, e.g.:

```vim
set rtp+=~/.vim/pack/bundle/start/ultisnips
set rtp+=~/.vim/pack/bundle/start/snippets
```

Then run `vim -u path/to/troubleshooting_vimrc.vim`. Do you still have the issue? If so, please explain the exact steps to reproduce it (including which filetype you are using).

**Comment by crivotz** [comment] 2018-11-07 13:34
Ok the problem is with vim-endwise.
I have not considered it before because in the `mucomplete-compatibility` you talk about the existence of the problem only for Vim versions lower than 8.0.0.282.
Maybe can be linked to this tpope/vim-endwise#108

**Comment by lifepillar** [comment] 2018-11-07 16:38
Ok, I see. Please try replacing this line:

```vim
inoremap <silent> <expr> <cr>
      \ mucomplete#ultisnips#expand_snippet("\<cr>")
```

with this:

```vim
inoremap <silent> <expr> <Plug>MyCr
      \ mucomplete#ultisnips#expand_snippet("\<cr>")
imap <cr> <Plug>MyCr
```

**Comment by crivotz** [comment] 2018-11-07 16:40
yes, it's works fine

**Comment by lifepillar** [comment] 2018-11-07 16:41
Good. Can you please post the output of `:verbose imap <cr>`? Thanks.

**Comment by crivotz** [comment] 2018-11-07 16:43
`i  <CR>          <Plug>MyCr<Plug>DiscretionaryEnd      `                                                                                                                            

and after I have a message like 'set last time by .../bundle/vim-endwise/plugin/endwise.vim'

**Comment by lifepillar** [comment] 2018-11-07 16:44
Great, that is like it is supposed to be. I need to update the documentation then. Thanks for your feedback!

**Comment by crivotz** [comment] 2018-11-07 16:46
Thanks for your work ;)

**Comment by whnr** [comment] 2019-03-15 20:57
@lifepillar the new solution in https://github.com/lifepillar/vim-mucomplete/issues/125#issuecomment-436689483 and fixed in https://github.com/lifepillar/vim-mucomplete/commit/62bae4d36755e2d64277eaa892e55e3cced0acb5 does not work if I don't use endwise but use AutoPairs.

There is a note on vim prior to 8.0.0282 in the help. And it definitely is autopairs, thats causing trouble. `verbose  imap <cr>` gives:
```
i  <CR>        &@mucomplete#ultisnips#expand_snippet("\<CR>")<SNR>22_AutoPairsReturn
        Zuletzt gesetzt in ~/.vim/pluggged/auto-pairs/plugin/auto-pairs.vim Zeile 662
i  <CR>          <Plug>MyCr
        Zuletzt gesetzt in ~/.vimrc Zeile 131
```
The old variant without `<plug>MyCr` works and gives:
```
i  <CR>        &@<SNR>22_AutoPairsOldCRWrapper73<SNR>22_AutoPairsReturn
        Zuletzt gesetzt in ~/.vim/pluggged/auto-pairs/plugin/auto-pairs.vim Zeile 662
i  <CR>        * mucomplete#ultisnips#expand_snippet("\<CR>")
        Zuletzt gesetzt in ~/.vimrc Zeile 133
```

Now I'm slightly confused if there is a universal solution to this mess.

**Comment by lifepillar** [comment] 2019-03-17 08:21
@whnr How about something like this:

```vim
  let g:AutoPairsMapCR = 0
  let g:AutoPairsMapSpace = 0
  imap <silent> <expr> <space> pumvisible()
    \ ? "<space>"
    \ : "<c-r>=AutoPairsSpace()<cr>"

  let g:UltiSnipsExpandTrigger = "<f5>"        " Do not use <tab>
  let g:UltiSnipsJumpForwardTrigger = "<c-b>"  " Do not use <c-j>

  inoremap <silent> <expr> <plug>UltiExpand
        \ mucomplete#ultisnips#expand_snippet("\<cr>")
  imap <plug>MyCR <plug>UltiExpand<plug>AutoPairsReturn
  imap <cr> <plug>MyCR
```

The idea is to disable Auto Pairs mappings (first two assignments above) and invoke them in custom mappings them instead (`imap <space>` and `imap <plug>MyCR`).

**Comment by whnr** [comment] 2019-03-19 23:11
@lifepillar That does work like a charm. Any reason for the double `imap`? I just tried the setting below and it works well.

````vim
inoremap <silent> <expr> <plug>UltiExpand
    \ mucomplete#ultisnips#expand_snippet("\<cr>")
imap <cr> <plug>UltiExpand<plug>AutoPairsReturn
````

**Comment by lifepillar** [comment] 2019-03-20 07:54
As explained in the manual:

>Mapping things this way will also make MUcomplete and auto-pairs work well together with endwise.vim.

If you don't use endwise, go and simplify your configuration.

**Closed** 2019-03-21 07:55 UTC
