### ISSUE TITLE
flicker when case is different

### ISSUE THREAD

**Issue by nhooyr** [lifepillar/vim-mucomplete#50] opened 2017-01-07 22:20 UTC
- [x] Output of `echo g:mucomplete#chains`: `{'vim': ['file', 'cmd', 'keyn'], 'default': ['file', 'omni', 'keyn', 'dict']}` 
- [x] Output of `setl completeopt`: `completeopt=menuone,noselect`
- [x] MUcomplete settings in my `.vimrc`, if any: enable at startup one

I also have `set noinfercase`.

When I type in a different case then the completion option, the completion popup begins to flicker and sometimes between the flickers I cannot press `<C-N>` to cycle anymore because it is flickering.

Watch: https://asciinema.org/a/dwx7i36veux6j7dfm055so2b4

**Comment by lifepillar** [comment] 2017-01-08 11:01
Well, that is kind of expected. For example, when you type `lily.listen`, the pop-up menu appears showing the available completions. Note that none starts exactly with `lily.listen`(because the case differs). So, when you type the next character, Vim notices that none of the shown completions match `lily.listena`, and closes the menu. When you type the next character, µcomplete autocompletion kicks in again, repeating the process. You may reproduce the behaviour without µcomplete: turn off auto-completion, just type `lily.listen<c-x><c-o>`, then type `a`: instead of restricting the available choices and keeping the menu open, Vim closes the menu.

It looks like Vim is inconsistent is this behaviour, compared to, say, keyword completion (where the menu stays there even if case does not match).

For now, you might limit (but not eliminate) the problem by giving `'keyn'` a higher priority (by putting it before `'omni'` in the completion chain), so that at least keywords that you have already written are completed without flickering.

**Comment by lifepillar** [comment] 2017-01-08 11:10
I have opened an issue in the Vim repo: https://github.com/vim/vim/issues/1361. Let's wait and see whether they consider it a bug.

**Comment by lifepillar** [comment] 2017-04-16 19:46
I didn't get any feedback about https://github.com/vim/vim/issues/1361, but the current master should solve this issue. Could you please try it and report your results? Take a look at the Readme or at the docs, because there are some additional settings to be put in your `vimrc`.

**Comment by nhooyr** [comment] 2017-04-16 19:51
Unfortunately, I do not have a machine with me that I can try it on. I will be getting a new laptop on the 20th so I will try to try then.

**Comment by lifepillar** [comment] 2017-04-20 19:33
I have installed vim-go and tried to edit a Go file. MUcomplete does not go on and off on alternating keys any more, as expected. Vim-go is slow as hell, though, so you may still see the pop-up menu disappearing and reappearing (but on the same key press) when the case of the keyword you are typing does not match the case of the completions. Unfortunately, until https://github.com/vim/vim/issues/1361 is addressed, I do not think that much more than that can be done.

**Comment by nhooyr** [comment] 2017-04-20 19:42
Alright, I received my new laptop. I will test this soon, thank you :)

**Comment by jordwalke** [comment] 2017-04-24 22:25
I noticed flickering when `mucomplete` switches between chains.

When the popup has this and is using omnicomplete:

<img width="410" alt="screen shot 2017-04-24 at 3 23 55 pm" src="https://cloud.githubusercontent.com/assets/977348/25361258/134fe18e-2902-11e7-816f-df9e9255288a.png">

And then I hit the next character `a`, which switches from 'omni' to 'incl', it changes to this, but for a brief moment in between there is a flicker.


<img width="255" alt="screen shot 2017-04-24 at 3 24 02 pm" src="https://cloud.githubusercontent.com/assets/977348/25361259/15026326-2902-11e7-9e3f-7b81303ef8e1.png">

Should I make a separate issue?

**Comment by lifepillar** [comment] 2017-10-27 10:02
So, according to https://github.com/vim/vim/issues/1361, case (in)sensitivity of omni-completion functions depends on how the omni-completion function is defined (in particular, on the `icase` parameter). I am closing this. Feel free to re-open if you want to provide more feedback.

**Closed by lifepillar** 2017-10-27 10:02 UTC
