### ISSUE TITLE
Cursor lags while autocompleting.

### ISSUE THREAD

**Issue by jordwalke** [lifepillar/vim-mucomplete#67] opened 2017-06-30 05:33 UTC
When typing with `mucomplete`, I noticed something was off. It seemed to complete fairly quickly, but the entire act of typing felt laggy or off. I've used many completion plugins and I haven't seen this before. So I took out my high speed camera 240fps and recorded the difference between typing without mucomplete and with mucomplete. I slowed down the recording and found that mucomplete causes characters to be inserted *before* the cursor moves! That totally explained it. When I disabled mucomplete, it did not suffer this problem.

![caught](https://user-images.githubusercontent.com/977348/27722202-ecce15b0-5d1a-11e7-8940-c8ed9ce03c39.jpg)

- [ ] Output of `echo g:mucomplete#chains`: …
`{'vim': ['path', 'cmd', 'ulti', 'keyn'], 'default': ['path', 'omni', 'incl', 'keyn', 'dict', 'uspl', 'ulti']}`
- [ ] Output of `setl completeopt`:`menu, menuone, noinsert`
- [ ] MUcomplete settings in my `.vimrc`, if any: …
```
set completeopt+=menuone
set completeopt-=preview

set completeopt+=noinsert
" inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
" inoremap <expr> <tab> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#no_mappings = 1



if v:version > 799
  let g:mucomplete#can_complete = {}
  let g:mucomplete#can_complete.default = {'omni': {t -> strlen(&l:omnifunc) > 0  && t =~# '\%(\l\l\|\u\|\.\)$' && (join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')) !~? 'comment\|string' || join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')) =~? 'commentCode')}}
  let g:mucomplete#chains = {
    \ 'default' : ['path', 'omni', 'incl', 'keyn', 'dict', 'uspl', 'ulti'],
    \ 'vim'     : ['path', 'cmd', 'ulti', 'keyn']
    \ }
endif

" Have to disable merlin mappings.
let g:merlin_disable_default_keybindings=1
exec "xnoremap <silent> . <s-tab> :call UltiSnips#SaveLastVisualSelection()<cr>gvs"

```

**Comment by lifepillar** [comment] 2017-06-30 14:05
Have you checked if that happens only when `omnifunc` is defined? My guess is that your custom check in `g:mucomplete#can_complete` is slowing down Vim. Functions like `synstack()` and `synIDattr()` are very slow.

**Comment by jordwalke** [comment] 2017-07-01 09:04
It still happens with `  let g:mucomplete#can_complete.default = {'omni': {t -> strlen(&l:omnifunc) > 0  && t =~# '\%(\l\l\|\u\|\.\)$'}}
`

**Comment by lifepillar** [comment] 2017-07-02 07:10
Please try `vim -u vimrc`, where `vimrc` is the following file (make sure to change the last line):

```vim
set nocompatible
set nobackup noswapfile
set noundofile
set nowritebackup
set viminfo=""
set packpath=
set runtimepath=$VIMRUNTIME
set completeopt=menuone,noinsert
syntax enable
filetype plugin indent on
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#no_mappings = 1

if v:version > 799
  let g:mucomplete#can_complete = {}
  let g:mucomplete#can_complete.default = {'omni': {t -> strlen(&l:omnifunc) > 0  && t =~# '\%(\l\l\|\u\|\.\)$' && (join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')) !~? 'comment\|string' || join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')) =~? 'commentCode')}}
  let g:mucomplete#chains = {
    \ 'default' : ['path', 'omni', 'incl', 'keyn', 'dict', 'uspl', 'ulti'],
    \ 'vim'     : ['path', 'cmd', 'ulti', 'keyn']
    \ }
endif

" Have to disable merlin mappings.
let g:merlin_disable_default_keybindings=1
exec "xnoremap <silent> . <s-tab> :call UltiSnips#SaveLastVisualSelection()<cr>gvs"

set runtimepath+=/PATH/TO/mucomplete " CHANGE THIS
```

Set the filetype to something that has support for omni-completion (say, `set ft=c`), and start typing. Can you still reproduce your issue?

**Comment by jordwalke** [comment] 2017-07-03 01:47
I don't see any issue when doing that but I think something's not even wired up correctly because I continually see this:

<img width="383" alt="screen shot 2017-07-02 at 6 43 28 pm" src="https://user-images.githubusercontent.com/977348/27775442-dcd3f880-5f56-11e7-9bec-2e930015f795.png">

**Comment by lifepillar** [comment] 2017-07-03 05:21
Do you mean, autocompletion doesn't fire? Please make sure that the `vimrc` is in `~/.vim/`, then try `cd ~/.vim && vim -u vimrc`.

**Comment by lifepillar** [comment] 2017-07-03 14:47
Sorry, I forgot that C completion requires a `tags` file. The reason omni-completion may not be working for you is that you have no `tags` file. You may try other filetypes, though.

**Comment by lifepillar** [comment] 2017-07-03 15:16
For the record, I cannot reproduce your issue in any perceivable way using the vimrc above (I have tried with several different filetypes).

**Comment by jordwalke** [comment] 2017-07-03 22:45
My filetype was just a `.md` plain text file on MacVim. Slow terminal refresh/update rates might be hiding it.

**Comment by lifepillar** [comment] 2017-07-04 06:26
Ok, I can reproduce it in MacVim. The culprit seems to be the syntax colouring, not the omnifunc. Can you try with `:syntax off`?

**Comment by jordwalke** [comment] 2017-07-04 09:56
I believe syntax off corrects, or at least mitigates the problem.

**Comment by lifepillar** [comment] 2017-07-05 20:54
That seems a MacVim-specific issue independent of µcomplete. To verify that, make sure µcomplete is off, then create a new buffer and execute:

```vim
:set ft=markdown
:autocmd TextChangedI * sleep 1
```

Enter Insert mode and start typing. You will clearly see that the character is inserted before the cursor is redrawn. The issue has something to do with syntax colouring because by disabling syntax colouring (or using a filetype not supporting syntax colouring, like plain text), the issue disappears. Also, the “Use Core Text renderer” setting does not seem to affect anything. Finally, in the terminal, the issue cannot be reproduced (I have tried with Terminal.app and iTerm2).

Probably worth opening an issue at [MacVim](https://github.com/macvim-dev/macvim).

**Comment by jordwalke** [comment] 2017-07-07 01:20
I never recalled seeing the same problem with AutoComplPop. Is it coincidence?

**Comment by lifepillar** [comment] 2017-07-07 06:28
AutoComplPop fires on `CursorMovedI` rather than `TextChangedI`. That might explain the difference.

Would you mind trying to replace this line in `autoload/mucomplete.vim`:

```vim
autocmd TextChangedI  * noautocmd call s:act_on_textchanged()
```

with

```vim
autocmd CursorMovedI  * noautocmd if !pumvisible() | call s:act_on_textchanged() | endif
```

and report back how it works for you?

**Comment by lifepillar** [comment] 2017-07-07 07:01
Btw, I have noticed that you have put `'incl'` in your completion chain. That may slow down autocompletion to the point that the phenomenon you are experiencing (which, as shown above, happens anyway) becomes noticeable. You may try to define a Markdown-specific chain without it, or at least put `'incl'` later in the chain.

MUcomplete likely does more computation per typed character than AutoComplPop, since, in general, it tries several completion methods each time (if I recall correctly, AutoComplPop chooses one based on the pattern before the cursor). But it shouldn't be too hard to make µcomplete behave like AutoComplPop, with suitable definitions of `mucomplete#can_complete` and `mucomplete#chains`.

**Comment by jordwalke** [comment] 2017-07-08 05:18
I don't really notice a difference replacing that line with `CursorMovedI`.

**Comment by lifepillar** [comment] 2017-07-08 06:19
Mmh, you are right. In fact, after

```vim
:autocmd CursorMovedI * sleep 1
```

the behaviour is the same as with `TextChangedI`, i.e., the cursor is redrawn after the character is inserted. Which is weird, because Vim's documentation states that `CursorMovedI` fires *after* the cursor has moved.

So, the only way to fix this issue (apart from reporting to MacVim devs) is to make µcomplete faster., which you do by carefully crafting your completion chains. Removing `'incl'` from your completion chain (at least in Markdown buffers) should improve the situation. In the default chain I would move `'incl'` after `'keyn'` anyway.

**Comment by jordwalke** [comment] 2017-07-09 22:00
Thanks. We previously discussed a way to combine all chains into one. That would eliminate some flickering but would make this problem worse, no?

**Comment by lifepillar** [comment] 2017-07-10 07:39
Possibly. I would rather try and fix the problem at the source, i.e., MacVim rendering.

**Comment by qazip** [comment] 2017-07-10 08:46
I notice the same behaviour using GVim and .tex files. I'm not using mu-complete though.

**Comment by lifepillar** [comment] 2018-02-03 09:39
I am closing this, as we have ascertained that the issue is rendering in GUI Vim and it is independent of µcomplete.

**Closed by lifepillar** 2018-02-03 09:39 UTC

**Comment by jordwalke** [comment] 2018-11-10 23:43
I'm noticing this pretty badly in gvim.exe. I know it might be a gui vim issue, but mucomplete should probably work well in all of its environments, and a large number of those are gui environments. Is there something you can do to fall back to a different implementation that doesn't have these downsides?

**Comment by lifepillar** [comment] 2018-11-11 10:40
I have reported this to Vim's repo some time ago (https://github.com/vim/vim/issues/2163) and it has been marked as a performance issue. You may ask to escalate the issue there.

The only workaround I have found is to turn syntax highlighting off (`:syntax off`). Other than that, you may only try to *reduce* the troubling effect.

Have you tried setting `let g:mucomplete#completion_delay` ? See `:help mucomplete#completion_delay` for further details.

If that does not help, could you please post the output of these commands:

```vim
:verbose autocmd CursorHoldI
:verbose autocmd CursorMovedI
:verbose autocmd InsertCharPre
:verbose autocmd TextChangedI
```

The next step would be to benchmark the code called during such events, find the bottleneck, and try to optimise it.

**Comment by lifepillar** [comment] 2018-11-11 10:56
@jordwalke Also, which filetypes are you using? Is it only Markdown, or other filetypes as well? Are you using dictionary and/or spelling completion?

**Comment by jordwalke** [comment] 2018-12-17 08:31
I have found that what is causing this on windows Gvim.exe is a combination of using `mucomplete` and `ultisnips`, even if I don't have ultisnips in the completion chain. Just merely having Ultisnips installed while `mucomplete` uses `omnicomplete` is sufficient to cause the issue (or make it much worse). I think the issue might be that two of you are fighting over some autocmd event.

**Comment by lifepillar** [comment] 2018-12-18 08:42
What about using UltiSnips, but not MUcomplete? Does the cursor lag in that case? If that is the case, perhaps is UltiSnips that is slowing you down. If not, does delaying completion (e.g, `set mucomplete#completion_delay = 500`) mitigate your issue?
