### ISSUE TITLE
E220: Missing }.

### ISSUE THREAD

**Issue by marovira** [lifepillar/vim-mucomplete#87] opened 2018-02-11 08:04 UTC
Hello,

I'm experiencing some problems while using mucomplete with vimtex. Basically, any time I type '{' I get the following error message: 

```
Error detected while processing function mucomplete#path#complete[11]..<SNR>115_glob:
line 1:
E220: Missing }.
```

It is worth noting that if I add the missing '}' and try to type within the braces (for example `\emph{something}` it will still generate the error.

* I have followed the instructions in `h:mucomplete-troubleshooting`
* My settings are:
```
echo g:mucomplete#chains
{'vim': ['path', 'cmd', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}
```

I have tried adding a custom chain for latex that removes the 'path' option, but this does not resolve the issue.

**Comment by lifepillar** [comment] 2018-02-11 11:44
I can reproduce this in Windows. As a temporary workaround, you may remove `{` from `isfname`:

```vim
set isfname-={
```

I'll fix it as soon as I understand how to properly escape special characters in Windows.

**Comment by lifepillar** [comment] 2018-02-11 11:46
>I have tried adding a custom chain for latex that removes the 'path' option, but this does not resolve the issue.

Since this is a bug in path completion, removing `'path'` from your completion chain should also fix it. How did you define your custom chain?

**Comment by lifepillar** [comment] 2018-02-11 17:24
Re-opening, because `fnameescape()` does not escape `{` in Windows if `{` is in `isfname`.

**Comment by marovira** [comment] 2018-02-11 18:05
I defined my custom chain by adding this to my vimrc:

```
let g:mucomplete#chains.tex = ['cmd', 'omni', 'dict', 'keyn', 'uspl']
```

I also tried `g:mucomplete#chains.latex` and that also didn't work.

**Comment by lifepillar** [comment] 2018-02-11 18:32
That should be ok: none of those methods should trigger the error you see. Maybe you could try them one at a time by setting `b:mucomplete_chain` to find which one is causing problems. For example, to use only omni-completion, type:

```vim
:let b:mucomplete_chain = ['omni']
```

then try to type something.

PS: Reopening, because in Windows even an escaped `{` gives an error… Need to understand `:h wildcards` better…

**Comment by lifepillar** [comment] 2018-02-11 19:36
Ok, the bug should be fixed in the current master.

**Comment by marovira** [comment] 2018-02-11 19:54
Thank you! The error doesn't appear anymore.

**Closed** 2018-02-11 20:08 UTC
Labels: bug
