### ISSUE TITLE
mucomplete triggered a character too early

### ISSUE THREAD

**Issue by trobjo** [lifepillar/vim-mucomplete#139] opened 2019-02-25 06:29 UTC
In F#, with language server support, mucomplete is a little broken. 
This is manual C-x C-o: 

![screenshot_2019-02-25-072640](https://user-images.githubusercontent.com/26080212/53318206-c15c9780-38ce-11e9-8aba-2cd67c404fd4.png)

And this is mucomplete:
![screenshot_2019-02-25-072745](https://user-images.githubusercontent.com/26080212/53318217-cfaab380-38ce-11e9-8736-7b0f11c47ae0.png)

It must be because it triggers the completion a character too early, because when I do C-x C-o before it looks like this:

![screenshot_2019-02-25-073012](https://user-images.githubusercontent.com/26080212/53318268-ff59bb80-38ce-11e9-9997-8ab0a7918db6.png)

My settings:

` let g:mucomplete#enable_auto_at_startup = 1`
` let g:mucomplete#can_complete = { 'default': {'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\%(\k\k\|\.\)$' } } }`
` let g:mucomplete#chains = { 'default': [ 'omni', 'file', 'incl'] }`

**Comment by trobjo** [comment] 2019-02-25 08:17
The filetype i fsharp. The syntax highlighting is not included in vim, but can be found in [polyglot](https://github.com/sheerun/vim-polyglot/blob/master/syntax/fsharp.vim)

I use [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) with [fsprojects/fsharp-language-server](https://github.com/georgewfraser/fsharp-language-server)

**Comment by trobjo** [comment] 2019-02-25 08:19
I otherwise use VimCompletesMe, and tabbing works as it should there.

**Comment by lifepillar** [comment] 2019-02-25 09:23
Can you please post your language server's configuration, too? Also, is this Vim or NeoVim? Which OS?

**Comment by trobjo** [comment] 2019-02-25 09:34
You can find a minimal vim config file that still reproduces the problem. https://transfer.sh/SPTQY/init.vim

I run Neovim 0.3.4 on Arch Linux. If you need the language server yourself but can't or won't do it yourself, then I'll be happy to upload it (but it takes up 74 MB).

**Comment by lifepillar** [comment] 2019-02-25 20:30
Can you try editing `autoload/mucomplete.vim` and replace the two `\<c-r>\<c-r>` in `s:try_completion()` with just one `'\<c-r>` (keep the backslash)? After that, do you get a different result when completion is triggered?

**Comment by lifepillar** [comment] 2019-02-25 22:08
You do not set `omnifunc`. But in my setup, `omnifunc` is empty. What should the value of `omnifunc` be?

**Comment by trobjo** [comment] 2019-02-26 04:34
I don't understand the last question. I don't think I have set omnifunc anywhere. But grepping for omnifunc in `LanguageClient-neovi` gives me this:

`src/language_server_protocol.rs`
`1818:            .command("setlocal omnifunc=LanguageClient#complete")?;`

**Comment by lifepillar** [comment] 2019-02-26 08:13
Ok, I've got the language server working. However, I cannot get `<c-x><c-o>` to complete anything, despite `:set omnifunc?` reporting `omnifunc=LanguageClient#complete`. I see the `dotnet` server process is running and I don't get any errors (apart from `No .fsproj or .fsx file references` on the first line). In particular, typing the text in your pictures doesn't offer me any completion.

Can you provide me with the steps to reproduce your issue (including a minimal F# file)?

**Comment by trobjo** [comment] 2019-02-26 16:05
I had huge problems getting the dotnet framework to work. Eventually I got it working by installing both the regular and -preview packages. I have these packages installed now:  `dotnet-host-preview`, `dotnet-runtime`, `dotnet-runtime-preview`, `dotnet-sdk`, `dotnet-sdk-preview` to get it working. 

To make autocompletion work, I just created a new dir, `test` in ~, so `test` becomes the project root. In `test` I just have a single .fsx file, `test.fsx`with a single line `printf "%A" "abcd".Length`.

Thank you for taking the time to troubleshoot my problems!

**Comment by lifepillar** [comment] 2019-02-28 19:12
Thanks, that was very helpful: now I can reproduce your issue as in your pictures. For the record, apparently completion works only if the filename has the correct suffix (I was using `.fs`: as soon as I switched to `.fsx` completion started to work). As for dotnet, I had to install only `dotnet-sdk` (that's in macOS).

Time to figure out why it completes that way…

**Comment by lifepillar** [comment] 2019-02-28 20:12
Mmh, there may be some synchronisation problem. Please edit `autoload/LanguageClient.vim` (in the LanguageClient plugin) and change function `LanguageClient#complete()` by adding `sleep 50m` right after `else`:

```vim
function! LanguageClient#complete(findstart, base) abort
    if a:findstart
        " Before requesting completion, content between l:start and current cursor is removed.
        let s:completeText = LSP#text()

        let l:input = getline('.')[:LSP#character() - 1]
        let l:start = LanguageClient#get_complete_start(l:input)
        return l:start
    else
      sleep 50m  " <== ADD THIS
        " Magic happens that cursor jumps to the previously found l:start.
```

Does that fix your issue?

**Comment by trobjo** [comment] 2019-02-28 20:17
Yes it does! Thanks a lot.

**Comment by lifepillar** [comment] 2019-02-28 20:22
Perhaps, even something as low as `sleep 1m` is enough.

**Comment by lifepillar** [comment] 2019-02-28 20:26
I haven't fully investigated how `LanguageClient#complete` works. It *may* be that MUcomplete exposes a LanguageClient bug.

**Comment by lifepillar** [comment] 2019-02-28 20:37
The minimum delay which seems to work reliably is `sleep 31m`.

**Comment by mg979** [comment] 2019-02-28 20:40
@trobjo said it works with VimCompletesMe, maybe MUcomplete does something different?

**Comment by lifepillar** [comment] 2019-02-28 20:51
@mg979 If you use tab completion, MUcomplete behaves like VimCompletesMe. This issue manifests itself only with auto-completion, AFAICT. MUcomplete's auto-completion doesn't do anything different (well, almost) from typing `<c-x><c-o>` for you after you type a character, but it does it much faster than you would. How this affects LanguageClient completion is not clear to me, but there surely is some timing issue.

**Comment by lifepillar** [comment] 2019-02-28 21:05
To elaborate on my last point, when debugging this issue using Vim's debugger, I could not reproduce it. For instance, add a breakpoint in a MUcomplete's function such as `try_completion()`; then, assuming that the cursor is at the end of `printf "%A" "A"`, type `.`. This enters the debugger. Type `cont` to exit the debugger immediately: you will see that the text is completed correctly. But if you remove the breakpoint and do the same, you'll get the wrong completions.

**Comment by mg979** [comment] 2019-02-28 21:07
Then the issue *could* be that MUcomplete is using a wrong completion type. If you set `MUcompleteNotify 2`, what kind of completion does it show?

Maybe it can happen, if a method was already active and pressing `.` doesn't refresh the method in use.

**Comment by lifepillar** [comment] 2019-02-28 21:19
I have also `let b:mucomplete_chain = ['omni']` to be sure that only omni-completion is used. Anyway, the wrong completions shown by the OP's pictures are clearly from omni-completion: in particular, you'll get them when you try to complete an empty text (try typing `<c-x><c-o>` at the start of a line). And before you ask, I have double checked that MUcomplete uses the right text before the cursor.

In fact, if you debug `LanguageClient#complete()` you will notice that upon the second call (as per `:help complete-functions`, it is called twice) its `a:base` parameter is empty, which sounds weird to me.

**Comment by mg979** [comment] 2019-02-28 21:27
Sorry then. What happens with `g:mucomplete#completion_delay`?

**Comment by lifepillar** [comment] 2019-02-28 21:31
If I had to fix this in MUcomplete, adding a delay between the last character typed by the user triggering completion would work:

```vim
fun! s:try_completion()
  sleep 50m  " <== ADD THIS
  return s:compl_mappings[s:compl_methods[s:i]] . "\<c-r>\<c-r>=''\<cr>\<plug>(MUcompleteVerify)"
endf
```

For obvious reasons, I am not very keen to purposely slowing down my plugin :-) But I am open to discussion.

**Comment by mg979** [comment] 2019-02-28 21:34
If this only happens with `auto`, doesn't `g:mucomplete#completion_delay` fix the problem?

**Comment by lifepillar** [comment] 2019-02-28 21:43
That's a good suggestion! Yes, it *mostly* works.

Where it fails, is when you have the pop-up menu open and you type a character that causes the menu to close because there is no match. In such cases, MUcomplete always retries completion without delay (because there may be some other method that has completions to offer).

For instance, if you start typing `Li`, Fsharp's omni-completion will offer a few completions (`Linq`, `List`, `LiteralAttribute`). If you keep typing `List.`, the moment you type `.` the menu is dismissed because there is no match any longer. But MUcomplete retries completion immediately. Since there is no delay in this situation, Fsharp's omni-completion will offer the wrong completions, as in the OP's pictures.

**Comment by mg979** [comment] 2019-02-28 21:53
Maybe where this happens (popup close and auto-reopen) you could check `g:mucomplete#completion_delay`, if it's being used you call its timer (if it must be called for this to work), rather than trying the completion immediately.

**Comment by lifepillar** [comment] 2019-02-28 21:59
That is a possibility, sure.

**Comment by trobjo** [comment] 2019-03-01 06:12
For what it's worth, even `sleep 1m` works for me.

**Comment by lifepillar** [comment] 2019-03-01 10:43
>Maybe where this happens (popup close and auto-reopen) you could check `g:mucomplete#completion_delay`, if it's being used you call its timer

The current master has a preliminary attempt at providing such behaviour. In the current master, `g:mucomplete#completion_delay` is honoured after popup close and auto-reopen. If this works, I plan to introduce a separate option in the future to control this behaviour.

@trobjo Could you try the current master? Instead of modifying LanguageClient's code, now you should be able to fix your issue by enabling delayed completion:

```vim
let g:mucomplete#delayed_completion = 100
```

(This assumes your Vim has `+timers`). You may adjust the delay (in ms) as you see fit.

>For what it's worth, even `sleep 1m` works for me.

It also worked for me in terminal Vim, but in MacVim I had to set a higher value.

**Comment by trobjo** [comment] 2019-03-02 10:19
Neovim does have timers (`echo has('timers')` gives me `1`), but it still doesn't work. I get the same result as in my initial post.

**Comment by lifepillar** [comment] 2019-03-02 12:49
Ops, sorry, the option is called `g:mucomplete#completion_delay`!

Also, remember to turn autocompletion off and on again after setting that option.

**Comment by trobjo** [comment] 2019-03-02 13:06
Thanks, it works now! Consider this issue closed. But I don't understand your last comment about turning it off and on again. I have this in my config, and the autopopup works flawlessly:
`let g:mucomplete#completion_delay= 2`
`let g:mucomplete#enable_auto_at_startup = 1`
`let g:mucomplete#can_complete = { 'default': {'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\%(\k\k\|\.\)$' } } }`
`let g:mucomplete#chains = { 'default': [ 'omni', 'file', 'incl'] }`

**Comment by lifepillar** [comment] 2019-03-02 20:01
>But I don't understand your last comment about turning it off and on again.

That is, if you set or change the option's value manually (by typing `:` to enter command mode), then you need to turn autocompletion off and on again for the change to take effect.

As I said, I plan to split `g:mucomplete#completion_delay` into two options, so I will leave this open for now. Keep an eye on the changes in the next release!

**Comment by mg979** [comment] 2019-03-02 20:10
@lifepillar Are you sure an edge case such as this one deserves an option? I think a delay of the order of 100ms is barely noticeable.

I'm asking this because, speaking of delays, I'd rather see an option for a delayed *verification* of the completion, so that (maybe) async and fuzzy completions from other plugins could be 'plugged in' as user completion types. Not sure if it's feasible though (that is, if completion verification can 'wait').

**Comment by lifepillar** [comment] 2019-03-03 06:56
Yes, but I might want MUcomplete to wait 1s before triggering completion, and not wait at all after that.

RE delaying *verification*, that might be doable. Can you open a new issue, and perhaps describe a real use case where that would help?

**Comment by lifepillar** [comment] 2019-03-07 15:42
As anticipated, I have added a new option (`g:mucomplete#reopen_immediately`) for finer control of the completion delay. Beside documenting the new option, MUcomplete's documentation now also contains a paragraph on how to solve the OP's issue, which essentially amounts to:

```vim
let g:mucomplete#completion_delay = 100
let g:mucomplete#reopen_immediately = 0
```

(The delay may be adjusted, of course.)

Therefore, I am closing this. Feel free to re-open, or open a new issue, if necessary.

**Closed by lifepillar** 2019-03-07 15:42 UTC
