### ISSUE TITLE
"Error detected while processing function mucomplete#act_on_textchanged[8]..mucomplete#init"

### ISSUE THREAD

**Issue by tngreene** [lifepillar/vim-mucomplete#73] opened 2017-09-08 14:59 UTC
Got another one for you:
I was editing my vimrc, had typed 
``l0e0t ``

and got 
``
Error detected while processing function mucomplete#act_on_textchanged[8]..mucomplete#init
line 3:
E712: Argument of get() must be a List or Dictionary
``

Pressed enter
```
Error detected while processing function <SNR>107_try_completion:
line 1:
E716: Key not present in Dictionary: 0
Press ENTER or type command to continue
Error detected while processing function <SNR>107_try_completion:
line 1:
E15 Invalid expression: s:compl_mappings[s:compl_methods[s:i]] . "\<c-r>\<c-r>=''\<cr>\<plug>(MUcompleteVerify)"
line 3:
E712: Argument of get() must be a List or Dictionary

and then it just repeats in a loop until I force quit the application
```

**Comment by tngreene** [comment] 2017-09-08 15:08
I turned on no_mapping and it still happened.

**Comment by lifepillar** [comment] 2017-09-08 16:43
Mmh, there may be a regression introduced by some recent change. Unfortunately, I cannot reproduce the issue using your description. I will take a deeper look, but in the meantime, I would really appreciate if you could provide a step-by-step way to reproduce it, possibly using the troubleshooting vimrc that comes with µcomplete.

**Comment by lifepillar** [comment] 2017-09-08 18:17
>and then it just repeats in a loop until I force quit the application

You shouldn't need to quit Vim. Try pressing CTRL-C (a few times).

**Comment by lifepillar** [comment] 2017-09-08 18:19
Also, please provide the output of:

```vim
echo get(b:, 'mucomplete_chain', 'undefined')
echo get(g:, 'mucomplete#chains', 'undefined')
```

**Comment by tngreene** [comment] 2017-09-26 15:05
Running with the troubleshooter provided, things appear to be perfectly stable.

``echo get(b:, 'mucomplete_chain', 'undefined')|echo get(g:, 'mucomplete#chains', 'undefined')``
produces
    
    undefined
    {'vim': ['path', 'cmd', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}

In addition:
    ``imap <c-r>``
is unmapped

What types of plugins could cause a conflict? I made sure Neoplete was disabled. I'll download the latest version and try again with my regular code.

**Comment by tngreene** [comment] 2017-09-26 15:45
Checking out the latest version seemed to help. Thanks!

**Comment by lifepillar** [comment] 2017-09-26 18:16
Good to know! I'm closing this then. Feel free to provide more feedback if necessary.

**Closed by lifepillar** 2017-09-26 18:16 UTC
